spring.application.name=Backend
spring.datasource.url=jdbc:mysql://localhost:3306/exam_system
spring.datasource.username=root
spring.datasource.password=Gowthami@89

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true